### PR TITLE
Scyth02 Counters and Supplies Updates

### PR DESCRIPTION
**Pull request by scyth02**
Implemented Supplies module.
Implemented Merchant module and removed old implementation.
Implemented trophy and captive counters.
Implemented new initiative marker model.
Updated initiative marker to account for seized.
Implemented new ambition module.
Implemented new out-of-play markers and logic.
Migrated action card area to zone code.
Updated face-up discard to use new marker and sort cards.
Updated imperial ship model to new one. Will require supply graphic update.
Removed container events from counters module.
Moved counters module from Controls to Global.
Added supplies module to Global including updates to onLoad and onObjectSpawn events.
Add player board and resource marker GUIDs to Global.
Added assets from McChews mode to assets.
Implemented Ambition Declared button on the Ambition Declared (ie 0) marker.
NOTE: An update to the game save is required for the supplies module to be fully functional.

### CODE REVIEW

**Comment by Quinnsicle** [comment]
You must pull and merge in main/master periodically to keep your branch up to date.

**Comment by scyth02** [comment]
> You must pull and merge in main/master periodically to keep your branch up to date. Also, you should always make sure your branch is up to date before making a pull request.

I believe I follow. I merged main into scyth02-updates on the scyth02-updates branch. Please let me know if anything else is required. With regards to TS_Save.json, I did download the latest one from main before I started making my changes, but because of how the file works I'm not too sure if I did it correctly. I simply accepted all my changes.

**Comment by Quinnsicle** [comment]
There are so many changes I think it probably would've been best to split each feature change into a separate branch. That way it's much easier to review and debug.

**Comment by Quinnsicle** [comment]
I noticed the face up discard is a long strip. I assume this is to display the discard, but it's not working. I also intentionally didn't splay them out because it's very important to preserve the order in case the facedown discard pile runs out of cards.

**Comment by Quinnsicle** [comment]
I noticed the face up discard is a long strip. I assume this is to display the discard, but it's not working. I also intentionally didn't splay them out because it's very important to preserve the order in case the facedown discard pile runs out of cards. Also, It appears to hop when you press the toggle button.

**Comment by scyth02** [comment]
> There are so many changes I think it probably would've been best to split each feature change into a separate branch. That way it's much easier to review and debug.

Is there a certain method you want me to apply retroactively to my current changes? With so many branches? I did try using the _tts-expander_ at one point but was unsuccessful.

**Comment by Quinnsicle** [comment]
You should create a new branch. For example, "faceup_discard". Then you should be able to use git cherry-pick to apply the commits related to the faceup discard changes from this branch to the new "faceup_discard" branch.

**Comment by Quinnsicle** [comment]
Hopefully if we stick to small, incremental changes, and try to have everything inside modules, tts-expander won't be necessary.

**Review by Quinnsicle — APPROVED** [review]
👍

**Pull request merged**
